# permissions for end users to edit machineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machineconfig-editor-role
rules:
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - machineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - machineconfigs/status
  verbs:
  - get
