# permissions for end users to edit nodeobservabilitymachineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeobservabilitymachineconfig-editor-role
rules:
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilitymachineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilitymachineconfigs/status
  verbs:
  - get
