# permissions for end users to view nodeobservabilitymachineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeobservabilitymachineconfig-viewer-role
rules:
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilitymachineconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilitymachineconfigs/status
  verbs:
  - get
