# permissions for end users to view nodeobservabilityruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeobservabilityrun-viewer-role
rules:
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilityruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilityruns/status
  verbs:
  - get
