
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- nonResourceURLs:
  - /debug/*
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - machineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - machineconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - machineconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilities/finalizers
  verbs:
  - update
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilities/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilityruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilityruns/finalizers
  verbs:
  - update
- apiGroups:
  - nodeobservability.olm.openshift.io
  resources:
  - nodeobservabilityruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - get
  - list
  - use
  - watch
